name:   regression tests

on:
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: '* 10 * * 1-5'

jobs:
  runTest:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Install chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: run test
        run: |
          mvn test -Dlocal=devicefarm -Dplatform=android
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: "**/surefire-reports/"

      - name: enviar notificação slack
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_CHANNEL: devops-automation-tests
            SLACK_COLOR: ${{job.status}}
            SLACK_MESSAGE: 'execução dos testes finalizada.'
            SLACK_TITLE: 'pipeline devops slack'
            SLACK_USERNAME: SUCESSO

      - name: enviar notificação slack
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: devops-automation-tests
          SLACK_COLOR: ${{job.status}}
          SLACK_MESSAGE: 'execução dos testes finalizada.'
          SLACK_TITLE: 'pipeline devops slack
          SLACK_USERNAME: FALHA
        #https://github.com/marketplace/actions/setup-chromedriver
        #https://github.com/marketplace/actions/setup-java-jdk
        #https://github.com/marketplace/actions/upload-a-build-artifact
        #https://github.com/marketplace/actions/slack-notify